name: Comentario por creación de archivo

on:
  files:
    - '**.txt'  # Puedes cambiar la extensión a la que quieras monitorear

jobs:
  comment-on-creation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Obtener el número del issue o pull request
        id: get_pr
        run: |
          # Aquí debes reemplazar 'your-repo' y 'your-owner' con los valores correctos
          echo "::set-output name=issue_number::$(gh issue list --repo your-owner/your-repo --state open --label 'creation-comment' | awk 'NR==1{print $1}')"
      - name: Publicar comentario
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.job.steps.get_pr.outputs.issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Gracias por crear el archivo!'
            })
